[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "bin/day1.rs"
name = "day1"

[[bin]]
path = "bin/day2.rs"
name = "day2"

[[bin]]
path = "bin/day3.rs"
name = "day3"